### ISSUE TITLE
Main text line with two Wolfian line numbers

### ISSUE THREAD

**Issue by arsimr16** [hmteditors/hc-il18#23]
Perseus and our hard copy edition of book 18 have lines 604 and 605 as two separate lines.  (τερπόμενοι is line 604 and δοιὼ δὲ κυβιστητῆρε κατ᾽ αὐτοὺς is line 605) The OCT has the text printed as one line labeled 18.604, 605.  The line does scan and appears in the Venetus A as one line so I'm not sure why it has two line numbers.  How should we document this in the index?  For now, I entered it as two separate lines and used the same image urn for both.  Is this an acceptable solution?

urn:cts:greekLit:tlg0012.tlg001.msA:18.604,"urn:cite:hmt:vaimg.VA250VN-0752@0.492,0.6762,0.409,0.0293"

**Comment by StephanieML** [comment]
I am going to talk about this with all the editors. This is cool.

I'm not sure how we want to deal with this amazing multiform, but as long as we've documented what we've done we can adjust it.

**Comment by caseydue** [comment]
West has a long note about this in his apparatus (in Latin of course!). I'm too brain dead to look at it tonight but will look at it tomorrow. Seems like something very interesting!

**Comment by caseydue** [comment]
Look at Odyssey 4.17-19:
τερπόμενοι: μετὰ δέ σφιν ἐμέλπετο θεῖος ἀοιδὸς
φορμίζων, δοιὼ δὲ κυβιστητῆρε κατ᾽ αὐτούς,
μολπῆς ἐξάρχοντος, ἐδίνευον κατὰ μέσσους.

Do you see? It seems that Wolf thought the "μετὰ δέ σφιν ἐμέλπετο θεῖος ἀοιδὸς
φορμίζων" should be here too, and included it in his edition. If I understand West, Ath [= Athenaeus????] believed they were there and that Aristarchus removed them. I may be missing something of what West says, but the gist is, all the manuscripts have just the one line here in Iliad 18  instead of the two line version we see in the Odyssey. Wolf caused the problem by adding the two line version to Iliad 18 and giving them two line numbers, even though all manuscripts have just one verse here in 18. This doesn't solve the mark up problem - more on that tomorrow after the editors have talked about it!

**Comment by StephanieML** [comment]
odi et amo

**Comment by StephanieML** [comment]
So the consensus seems to be that we do not want to use the Wolfian lines because they don't exist as such in this manuscript. Instead we will use the text reference: `urn:cts:greekLit:tlg0012.tlg001.msA:18.604_605` to index it as a single line. In the Iliad text edition the @n value on the line should be `604_605`

**Comment by brclar15** [comment]
awesome, we'll change our editions to match that

**Comment by brclar15** [comment]
we are changing the lines to reflect this decisions in our editions and the indices. 
However, Professor Smith drops the same venA-textToFolio-Iliad.csv file in all of the VA repos, so our local change wont globally change the file. just a heads up

**Comment by StephanieML** [comment]
make an issue about how that file needs to be brought over into the archive when we're done then

**Comment by brclar15** [comment]
the issue has been made
